@startuml
'https://plantuml.com/activity-diagram-beta

|Customer|
start
:Choose a carport option;
if ( )  then (Standard carport)
end
-[hidden]
else  (Customized carport)
:Customize the carport;
|Webshop|


|Salesrepresentant|

@enduml
