@startuml
'https://plantuml.com/activity-diagram-beta

|Customer|
start
:Choose a carport type;
fork
:Standard carport;
fork again
:Customized carport;
|Webshop|
:Login;
|Customer|
:Customize the carport;
:Do you want a shed?;
fork
:yes;
:Customize the shed;
fork again
:no;
end fork
end fork
:Send order request]
|Webshop|
:Order request]
if (Order) then (Standard carport)
:Standard carport;
else (Customized carport)
|Salesperson|
:Notification]
:Salesperson qualifies request;
:Salesperson can calculate financial coverage rate;
:Salesperson can edit offer;
:Salesperson sends details;
endif
|Customer|
:Order details]
:Customer confirms details;

fork
:Standard carport;
:Customer provides personal information]
:Payment;
fork again
:Customized carport;
:Customer information available via login]
:Payment;
|Webshop|
:Orderpayment registers]
|Salesperson|
:Notification]

|Customer|
end fork
if () then (Standard carport)
:Order details forwarded]
else (Customized carport)
:Customized details forwarded]
endif
end

@enduml
