@startuml
'https://plantuml.com/activity-diagram-beta

|Customer|
start
:Choose a carport type;
fork
:Standard carport;
fork again
:Customized carport;


:Customize the carport;
:Do you want a shed?;
fork
:yes;
:Customize the shed;
fork again
:no;
end fork
end fork

|Customer|
:Send order request]

|Webshop|
if (Is the user logged in?) then (Yes)
else (No)
:Login;
endif
:Order request]


if () then (Standard carport)
:Standard carport;
else (Customized carport)
|Salesperson|
:Notification]
if (Is the salesperson logged in?) then (Yes)
else (No)
:Login;
endif
:Salesperson qualifies request;
:Salesperson can calculate financial coverage rate;
:Salesperson can edit offer;
:Salesperson sends details;
endif
|Customer|
:Order details]
:Customer confirms details;

fork
:Standard carport;
:Customer provides personal information]
:Payment;
fork again
:Customized carport;
:Customer information available via login]
:Payment;
|Webshop|
:Orderpayment registers]
|Salesperson|
:Notification]

|Customer|
end fork
if () then (Standard carport)
:Order details forwarded]
else (Customized carport)
:Customized details forwarded]
endif
end

@enduml
